; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:base]
platform = espressif32
;board = esp32cam
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
lib_deps = h2zero/NimBLE-Arduino@^2.1.0
           https://github.com/LennartHennigs/ESPTelnet
           BasicOTA
           PubSubClient
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
        '-D WIFI_SSID="${sysenv.WIFI_SSID}"'
        '-D WIFI_PASSWORD="${sysenv.WIFI_PASSWORD}"'
        '-D MQTT_SERVER="${sysenv.MQTT_SERVER}"'
        '-D MQTT_USER="${sysenv.MQTT_USER}"'
        '-D MQTT_PASSWORD="${sysenv.MQTT_PASSWORD}"'
        -D MQTT_PORT=${sysenv.MQTT_PORT}

[env:ota]
extends = env:base
upload_protocol = espota
upload_port = smokerproxy.local
monitor_port = socket://smokerproxy.local:23
